FROM mcr.microsoft.com/azure-cli:latest

COPY new-ripa-cssa-sub-domain.sh /new-ripa-cssa-sub-domain.sh

# ENV SP_APP_ID="" SP_SECRET="" TENANT_ID="" SUBSCRIPTION="" RESOURCE_GROUP_NAME="" CDN_PROFILE_NAME="" DNS_ROOT_ZONE="" AGENCY_ABBREVIATION="" APPLICATION_NAME="" KEY_VAULT_NAME="" SECRET_NAME="" WEB_CONTENT_URL="" 
CMD "/new-ripa-cssa-sub-domain.sh"