# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
        working-directory: UI
      - name: run linters
        uses: wearerequired/lint-action@v1
        with: 
          eslint: true
          prettier: true
          auto-fix: true
