# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build/Test

on:
  pull_request:
    branches: [main, dev-v2]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: install node.js dependencies
        run: npm install
        working-directory: UI

      - name: run jest unit tests
        run: npm run test:unit
        working-directory: UI

      - name: run xunit unit tests
        run: dotnet test
        working-directory: Functions
